name: Build and Release Extension Charts

on:
  workflow_dispatch:
  release:
    types: [released]
  workflow_call:
    inputs:
      target_branch:
        required: true
        type: string
      tagged_release:
        required: true
        type: string

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build-extension-charts:
    uses: rancher/dashboard/.github/workflows/build-extension-charts.yml@master
    permissions:
      actions: write
      contents: write
      deployments: write
      pages: write
    with:
      target_branch: main
      tagged_release: my-app
